# Generated by Django 5.2.12 on 2026-03-18 00:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='monthlycategorybudget',
            name='uniq_budget_user_category_year_month',
        ),
        migrations.RemoveConstraint(
            model_name='monthlycategorybudget',
            name='budget_month_1_12',
        ),
        migrations.RemoveIndex(
            model_name='monthlycategorybudget',
            name='expenses_mo_user_id_1d6dc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='expenses_tr_user_id_228bc5_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='expenses_tr_user_id_8623fd_idx',
        ),
        migrations.RemoveField(
            model_name='monthlycategorybudget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='monthlycategorybudget',
            name='year',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlycategorybudget',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expenses.monthlyreport'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.monthlyreport'),
        ),
        migrations.AddIndex(
            model_name='monthlycategorybudget',
            index=models.Index(fields=['user', 'report'], name='expenses_mo_user_id_319083_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'report', 'date'], name='expenses_tr_user_id_744f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'report', 'category', 'date'], name='expenses_tr_user_id_8fa2dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlycategorybudget',
            constraint=models.UniqueConstraint(fields=('user', 'report', 'category'), name='uniq_budget_user_category_year_month'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['user', 'year', 'month'], name='expenses_mo_user_id_5dc361_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='uniq_monthly_report_user_year_month'),
        ),
    ]
